### ISSUE TITLE
3. As a user, I want to set up a new shopping list so I can track purchased items

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#4]
A shopping list consists of a set of items associated with a user’s token. Creating a new list consists of the following:

* Generate a new, unique token
* Save the token to `localStorage`
* Show the user the list view

The following script can be used to generate a suitable token: https://gist.github.com/segdeha/21a42618ce5a54916c5b58d36ec2992e

AC:

* For users who do not already have a token/list, a button or link exists at the `/` route (i.e. home screen) that allows them to create a new list
* Clicking the button/link generates a new token and saves it to `localStorage`
* Once the token has been created and saved, the user is redirected to the "list" view

**Comment by nabilkaz** [comment]
Part 1 todos:
- [x] Briefly research and describe what `localStorage` is
- [x] Review the token generator gist
- [x] Break down the problem into smaller parts
- [x] Identify the relationship between the app, token, localStorage, lists and firebase

**Comment by nabilkaz** [comment]
Links that might be helpful for us to review:
`localStorage` documentation - https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
Firestore documentation - https://firebase.google.com/docs/firestore/quickstart

**Comment by nabilkaz** [comment]
Here's the app architecture:
![image](https://user-images.githubusercontent.com/3664197/81509562-596e5300-92c0-11ea-9e73-48ee30a3a293.png)

I think our story is going to focus on creating the functionality for this part of the app:
![image](https://user-images.githubusercontent.com/3664197/81509573-6c812300-92c0-11ea-906d-604813bb28ce.png)

**Comment by alejandronanez** [comment]
@nabilkaz @Tanzi11 👋 

To complement what we talked about in our call - we should use the generated token to create unique lists (thanks @nabilkaz for the diagrams above!)

![](https://cdn.zappy.app/cdf670604a907179562ec4fca18df1cf.png)

**Comment by nabilkaz** [comment]
Waiting on [PR#21](https://github.com/the-collab-lab/tcl-7-smart-shopping-list/pull/21) to be merged before starting a new branch 👍🏽

**Comment by nabilkaz** [comment]
Created new branch `NK-TR-create-tokenized-list`

**Comment by nabilkaz** [comment]
Broke down problem into two states:

**If (no list)**

1. event - create list event
2. create - token
3. Store in localStorage
4. Send to fire-store
5. Use token to create list with token identifier
6. And shows user tokened list view

**If (existing list)**

1. Get list based on token id
2. Show user tokened list view

**Comment by nabilkaz** [comment]
New todos:
- [x] Load token.js into app
- [x] Identify where event will live
- [x] Create event-handler that creates token and stores in `localStorage`
- [x] Create method for creating list based on token to firebase
- [x] Create view that shows token list from firebase

**Comment by nabilkaz** [comment]
We researched `localStorage` via the MDN documentation that allows you to use the `Storage` object to store data across browser sessions. By using the method `setItem(key, value)` you can store a key-value pair that will persist across sessions. 

Here is a video review of using `localStorage`: https://www.loom.com/share/9870282bd78049599e7a701381d4e525

**Comment by nabilkaz** [comment]
Next, we were able to add the `token.js` gist to `./lib` and import it into `App.js`.
We did an initial spike to make sure we could create a token and store it to the `localStorage`.
To do this we first created a token and used `console.log` to make sure it was generating.
Then we stored it to `localStorage` by using `window.localStorage.setItem('token', [generated-token])`.
It all worked out.

Our current thinking and outstanding questions:
- We still need to figure out how to organize the code. These are not components so they should probably live in `./lib`
- We've identified two user states: `hasList` ->  `true` or `false`
    - if `true` we would know by finding the token in the `localStorage` and using `getList` to the list view
    - if `false` generate a token when user starts new list and submit it to firebase to house 
- How should we handle creating a new list in firebase?

**Comment by nabilkaz** [comment]
I came across this article on REST API's this morning. _I think_ it explains some of the functionality that we're creating. We aren't implementing a thorough authentication feature but we are creating a token-based authentication that tells our program this user is authorized to view the list represented by the given token as represented by their `localStorage`.  

https://www.andrewhavens.com/posts/20/beginners-guide-to-creating-a-rest-api

> The solution to this is to use token based authentication. The user logs in with their username and password and the application responds with a unique token that the user can use for future requests. This token can be passed onto the application so that the user can revoke that token later if they choose to deny that application further access.

**Comment by nabilkaz** [comment]
We got hung up on how to create a new `list`. We first assumed that we had to create it via adding a new `collection` via the `fb` object but after reading the [documentation on data modeling](https://firebase.google.com/docs/firestore/data-model) there is a line that explicitly states: 

> Collections and documents are created implicitly in Cloud Firestore. Simply assign data to a document within a collection. If either the collection or document does not exist, Cloud Firestore creates it.

Which means if we modified the pathname on `./src/components/getList.js` on line 8 to changing `items` to a new name it should create that collection in the database:
```javascript
// ./src/components/getList.js
...
      <FirestoreDocument
        path="items/tIA3kp24eSWYTNKxA3wl"
        render={({ isLoading, data }) => {
...
```

Yet to test this but I think if we title it anything besides `items` we should see this reflected in the firestore database.

**Comment by nabilkaz** [comment]
It worked! Where I suggested to do it was wrong. The proper place to try and see if you can implicitly create a collection is in `addItems.js` file by changing line 19:

```javascript
    // ./src/components/addItem.js
    // replaced 'items' with 'newList' and checked firebase
    db.collection('newList').add({
      itemName: this.state.itemName,
    });
```
Because `newList` doesn't exist in firestore it'll create a collection with that name. 

![image](https://user-images.githubusercontent.com/3664197/81747983-eac6fc00-945d-11ea-859a-3e5e067e5915.png)



That means we should: 
1. Check if user has token in their `localStorage`
    * if so render `./list-view` else show sign in page with option to enter share code or create new list.
2. If user doesn't have token and clicks `create a new list` add token to their `localStorage` and sends user to `./add-item` 
3. When user adds an item. The collection name on line 19 in file `addItem.js` reflects token found on `localStorage`. 
4. When item is added it will create a collection in firestore with the token name and add the new document (shopping item). 
5. When navigating to ./list-view if token exists on firestore it should render that list.

**Comment by nabilkaz** [comment]
Doing styling for the welcome page and taking a function approach to css (basing it off of tachyons https://tachyons.io/). This means instead of describing the object in CSS. IE - building out a `card` class that has shadow, background color, etc. I build a `drop-shadow` class and `bg-blue` class and apply each class to the HTML element to style each part.

**Pros**: It makes it much easier to get in and style new elements once you understand the class syntax. 
**Cons**: Functional css can be very atomic so you don't get the simplicity of using a single `card` class (but that's what React components are for right?)

It's organized at the bottom of `app.css` starting on line 75 at the comment `/* Functional styles */`.

**Comment by nabilkaz** [comment]
Here's a video walkthrough of using functional CSS: https://www.loom.com/share/c2f3290a268f4df9b2b3fa6d3e4b20a9

**Comment by nabilkaz** [comment]
Ran the accessibility extension and found two errors:
1. Gray in the sample app (#999999) doesn't pass the accessibility checker (which requires a 4.5 rating). Replaced with #767676 which has a 4.54 contrast ratio rating.
![image](https://user-images.githubusercontent.com/3664197/81955695-465ccb00-95bf-11ea-9341-24d9c2654d54.png)
![image](https://user-images.githubusercontent.com/3664197/81955785-612f3f80-95bf-11ea-9d0f-36beaf4fc2a3.png)

2. When tabbing it would tab twice to the button "create a shopping list". This was because I had wrapped the button with an anchor tag so I could use onClick and route to a new path. Instead I replaced it with an action property that points to the intended path `./add-item`. Now it doesn't double tab to the "create a shopping list" button.

Here's the new tabbing behavior. Works great :)
![image](https://user-images.githubusercontent.com/3664197/81955557-16152c80-95bf-11ea-9e25-e481704ca95a.png)
