### ISSUE TITLE
5. As a user, I want to join an existing shopping list so I can share a shopping list with someone

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#6]
Tokens can be shared with other users to allow them to co-manage a given list.

Joining an existing list consists of the following:

* User enters an existing token
* Save the token to `localStorage`
* Show the user the existing list

AC:

* When the user does not already have a token in `localStorage`, on the onboarding/home screen, the user can enter an existing token
* Entering the token and hitting submit saves the token to `localStorage`, effectively giving them joint control of the list
* On submit, show an error if the token does not exist
* If they get an error message, allow them to try again or create a new list

**Comment by nabilkaz** [comment]
Here's a breakdown of the logic we're trying to recreate:
![image](https://user-images.githubusercontent.com/3664197/82222833-af518500-98d6-11ea-8ac3-5b08dc4fdd02.png)

**Comment by nabilkaz** [comment]
Here is our project breakdown:
1. Clicking "Join existing shopping list" should take us to "./join-list"
2. "./join-list" we should have the capacity to enter a share code
3. When share is submitted we need the capacity to validate share code
    - if share code is valid we need to:
        -  Set token of list to `localStorage`
        - Route to `./list-view`
    - If share is invalid we pop up an alert window

**Comment by nabilkaz** [comment]
### Our todo items:

**Page-level:**
- [x] Create 'JoinList` component that lets you enter a share code
- [x] Capacity to get share code value from input field
- [x] Capacity to create alert

**DB:**
- [x] Validate share code exists in Firestore

**Token:**
- [x] Capacity store share code as a token to the local storage

**Comment by nabilkaz** [comment]
Learning: 
Updated the `setLocalToken` function to accept a `token` argument. If a `token` is passed to the function then it will pass it to the logical OR to test if an argument was passed to the function. If not it will set the result of `getToken()` to token and set that to `localStorage`

![image](https://user-images.githubusercontent.com/3664197/82231023-66eb9480-98e1-11ea-832d-1d91c5002a31.png)

The issue we ran into was that it kept saving `[Object object]` to the localStorage. We learned that this was because we were passing `setLocalToken` directly to the Event Listener which implicitly passes the `event` object to the handler. We fixed this by having an event handler `handleClickSetLocalToken` that handles the event object and calls the `setLocalToken` function.

![image](https://user-images.githubusercontent.com/3664197/82231212-b29e3e00-98e1-11ea-9ea4-ef0638c48473.png)

LESSON: Always remember that event handlers are passed the event object implicitly. 
Loom Walkthrough: https://www.loom.com/share/e2196ba5a5514932b5085428f4fb45b4

**Comment by meganmckissack** [comment]
In building out the join existing list functionality, we we needed to test the shared code a user enters vs one that exists in the firebase database.  Since our collection names are generated by the user tokens, we needed to query all the stored collection names, which, according to the [firebase documentation](https://firebase.google.com/docs/firestore/query-data/get-data) uses a different method than querying firebase documents.
![Get_data_with_Cloud_Firestore_Firebase](https://user-images.githubusercontent.com/2355543/82350714-8e5d6280-99b0-11ea-93bd-15d92e7a5bad.png)

This medium article provided a clearer explanation of two common firebase query types and how to use them. [https://medium.com/@scarygami/cloud-firestore-quicktip-documentsnapshot-vs-querysnapshot-70aef6d57ab3](https://medium.com/@scarygami/cloud-firestore-quicktip-documentsnapshot-vs-querysnapshot-70aef6d57ab3).

We were able to get log the result of the firebase collection query as well as log the input value of the share code a user submits but ran into an issue testing the input value to match the firebase query after the submit event by the user.  There is an alert set to inform the use the code is not valid as it doesn't match a user token (firebase collection) but it returns the same alert if a known token is entered and logs `undefined` in the console.

Nabil found a [resource](https://www.youtube.com/watch?v=PJeNReqyH88) that we're going to research to explore debugging methods in react.

**Comment by meganmckissack** [comment]
@nabilkaz - I tried a couple of things to see if returning a value from the hasList function updated the share code handler but ` console.log(this.hasList(token));` still returned `undefined`.  

I used this get all data function from the medium article
`querySnapshot.forEach(function (collectionSnapshot) {`
  `var data = collectionSnapshot.data();`
  `console.log(data)`
  `return data`
`});`
It logged the document data of the user collection but `console.log(this.hasList(token));` still returned undefined

I also tried adding `.where('token', '=', token)` before the get method part of querying the database but on submit overrode the default prevention and sent me to the add item page.

Do you think we need to capture another type of value from the hasList component?

**Comment by meganmckissack** [comment]
Tried rewriting `hasList` firebase query snapshot using async await.  I also set a state update to capture the token input and added moved that to the param of the collection query, it now returns true or false value but the `handleShareCode` function is logging `this worked` if I put in both an known collection name and one I know doesn't exist.  

<img width="1170" alt="Screen Shot 2020-05-21 at 1 28 35 PM" src="https://user-images.githubusercontent.com/2355543/82604047-821c0580-9b68-11ea-91e5-4214857c2f01.png">

<img width="1129" alt="Screen Shot 2020-05-21 at 1 28 07 PM" src="https://user-images.githubusercontent.com/2355543/82604062-8cd69a80-9b68-11ea-94a8-3631ef0f0dab.png">

Found this [stackoverflow question](https://stackoverflow.com/questions/52100103/getting-all-documents-from-one-collection-in-firestore/52101894) using async await with firebase
